# Generated by Django 4.0.3 on 2022-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('created_by', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='%d-%m-%Y %H:%M:%S')),
                ('updated_by', models.IntegerField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='%d-%m-%Y %H:%M:%S')),
            ],
        ),
    ]
